const categories = [
  {
    id: 'painting',
    name: 'מוצרי צביעה',
    icon: '🎨',
    color: '#e63946',
    subcategories: [
      { id: 'rollers_pads',         name: 'רולרים ורפידות' },
      { id: 'trays_sets',           name: 'מגשים וסטים' },
      { id: 'paints',               name: 'צבעים' },
      { id: 'spray',                name: 'ספריי' },
      { id: 'solvents',             name: 'ממיסים' },
      { id: 'sandpaper',            name: 'נייר שמיר' },
      { id: 'primers',              name: 'פריימר ובסיס' },
      { id: 'painting_accessories', name: 'אביזרי צביעה' },
    ],
  },
  {
    id: 'kitchen',
    name: 'מוצרי מטבח',
    icon: '🍳',
    color: '#2a9d8f',
    subcategories: [
      { id: 'sinks',               name: 'כיורים' },
      { id: 'kitchen_faucets',     name: 'ברזי מטבח' },
      { id: 'cookware',            name: 'כלי בישול' },
      { id: 'storage_kitchen',     name: 'אחסון מטבח' },
      { id: 'cleaning_kitchen',    name: 'ניקוי מטבח' },
      { id: 'accessories_kitchen', name: 'אביזרי מטבח' },
    ],
  },
  {
    id: 'bathroom',
    name: 'מוצרי אמבטיה',
    icon: '🚿',
    color: '#457b9d',
    subcategories: [
      { id: 'mirrors',          name: 'מראות' },
      { id: 'shower_curtains',  name: 'וילונות מקלחת' },
      { id: 'towel_hooks',      name: 'ווים ומגבות' },
      { id: 'storage_bath',     name: 'אחסון אמבטיה' },
      { id: 'accessories_bath', name: 'אביזרי אמבטיה' },
      { id: 'toiletries',       name: 'טואלטיקה' },
    ],
  },
  {
    id: 'tools',
    name: 'כלי עבודה',
    icon: '🔧',
    color: '#e9c46a',
    subcategories: [
      { id: 'general_tools',    name: 'כלי עבודה כלליים' },
      { id: 'fastening',        name: 'הידוק וחיבור' },
      { id: 'measuring',        name: 'מדידה וסימון' },
      { id: 'sanding_surface',  name: 'שיוף ומשטחים' },
      { id: 'spray_tools',      name: 'כלי ריסוס' },
      { id: 'gas_flame',        name: 'להבה וגז' },
      { id: 'automotive',       name: 'כלי רכב' },
      { id: 'safety',           name: 'בטיחות' },
    ],
  },
  {
    id: 'cleaning',
    name: 'ניקיון',
    icon: '🧹',
    color: '#6a4c93',
    subcategories: [
      { id: 'mops',           name: 'מגבים ומטאטאים' },
      { id: 'brushes',        name: 'מברשות' },
      { id: 'chemicals',      name: 'חומרי ניקוי' },
      { id: 'cloths',         name: 'סמרטוטים וספוגים' },
      { id: 'disinfectants',  name: 'חיטוי' },
      { id: 'floor_cleaning', name: 'ניקוי רצפות' },
      { id: 'bags_packaging', name: 'שקיות ואריזות' },
    ],
  },
  {
    id: 'garden',
    name: 'גינה',
    icon: '🌿',
    color: '#52b788',
    subcategories: [
      { id: 'watering',     name: 'השקיה' },
      { id: 'garden_tools', name: 'כלי גינון' },
      { id: 'plant_care',   name: 'טיפוח צמחים' },
      { id: 'outdoor',      name: 'חוץ וגינה' },
    ],
  },
  {
    id: 'plumbing',
    name: 'אינסטלציה',
    icon: '🔩',
    color: '#0077b6',
    subcategories: [
      { id: 'plastic_connectors', name: 'חיבורים פלסטיים' },
      { id: 'feed_valves',        name: 'ברזי הזנה' },
      { id: 'nipples',            name: 'ניפלים ומחברים' },
      { id: 'water_heating',      name: 'חימום מים' },
      { id: 'faucet_accessories', name: 'אביזרי ברז' },
      { id: 'pipes',              name: 'צינורות' },
      { id: 'waterproofing',      name: 'איטום' },
      { id: 'drainage',           name: 'ניקוז' },
    ],
  },
  {
    id: 'adhesives',
    name: 'דבקים',
    icon: '🔫',
    color: '#f4a261',
    subcategories: [
      { id: 'cartridges',      name: 'מחסניות' },
      { id: 'sealants',        name: 'סיליקון ואיטום' },
      { id: 'spackle_adhesive',name: 'שפכטל ודבק' },
      { id: 'maoz',            name: 'מאוץ' },
      { id: 'spray_adhesives', name: 'דבק ספריי' },
      { id: 'foams',           name: 'קצף' },
      { id: 'putty_primer',    name: 'פרידי ופריימר' },
    ],
  },
  {
    id: 'locks',
    name: 'פירזול צילינדרים ומנעולים',
    icon: '🔐',
    color: '#343a40',
    subcategories: [
      { id: 'cylinders',        name: 'צילינדרים' },
      { id: 'padlocks',         name: 'מנעולי תלייה' },
      { id: 'door_locks',       name: 'מנעולי דלת' },
      { id: 'door_hardware',    name: 'פירזול דלתות' },
      { id: 'magnetic_locks',   name: 'מנעולים מגנטיים' },
      { id: 'code_locks',       name: 'מנעולי קוד' },
      { id: 'security_chains',  name: 'שרשראות ביטחון' },
      { id: 'bolts_latches',    name: 'בריחים וסרגלים' },
      { id: 'keys_accessories', name: 'מפתחות ואביזרים' },
    ],
  },
  {
    id: 'faucets',
    name: 'ברזים',
    icon: '🚰',
    color: '#48cae4',
    subcategories: [
      { id: 'kitchen_faucets_f',   name: 'ברזי מטבח' },
      { id: 'bathroom_faucets',    name: 'ברזי אמבטיה' },
      { id: 'garden_faucets',      name: 'ברזי גינה' },
      { id: 'valves',              name: 'שסתומים' },
      { id: 'accessories_faucets', name: 'אביזרי ברזים' },
    ],
  },
  {
    id: 'electrical',
    name: 'מוצרי חשמל',
    icon: '⚡',
    color: '#f4c430',
    subcategories: [
      { id: 'power_strips',   name: 'רב-שקעים' },
      { id: 'sockets_plugs',  name: 'שקעים ותקעים' },
      { id: 'splitters',      name: 'מפצלים' },
      { id: 'switches',       name: 'מפסקים' },
      { id: 'cables',         name: 'כבלים' },
      { id: 'timers',         name: 'שעוני זמן' },
      { id: 'remotes',        name: 'שלטים' },
      { id: 'lighting',       name: 'תאורה' },
      { id: 'protection',     name: 'הגנה חשמלית' },
      { id: 'accessories_el', name: 'אביזרי חשמל' },
    ],
  },
  {
    id: 'home',
    name: 'בית',
    icon: '🏠',
    color: '#8338ec',
    subcategories: [
      { id: 'anchors_dowels',        name: 'עוגנים ודיבלים' },
      { id: 'construction_materials',name: 'חומרי בניה' },
      { id: 'hanging_storage',       name: 'תלייה ואחסון' },
      { id: 'pest_control',          name: 'הדברה' },
      { id: 'tv_accessories',        name: 'אביזרי טלוויזיה' },
      { id: 'child_safety',          name: 'בטיחות ילדים' },
      { id: 'packaging',             name: 'אריזה' },
      { id: 'pergola',               name: 'פרגולות' },
      { id: 'general_home',          name: 'כללי בית' },
    ],
  },
];

export default categories;
